### ISSUE TITLE
Error trying to compile PTaH Version

### ISSUE THREAD

**Issue by 3GaNwO** [Franc1sco/Franug-BlockSMPlugins#1]
![Screenshot_1](https://user-images.githubusercontent.com/28633574/70120481-8471be00-1621-11ea-8962-07d853d80cda.jpg)

Attached will be the error I get upon trying to compile this. 

I did put the include files in as well

**Comment by Franc1sco** [comment]
Update your ptah include

**Comment by 3GaNwO** [comment]
Thank you this worked!
